name: "Export project"
on: push

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: griddy-code
  PROJECT_PATH: .

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot CI
        uses: abarichello/godot-ci@4.2.2-stable
